feed_url: "https://raw.githubusercontent.com/giuksbr/finance_feed/refs/heads/main/feed.json"

storage:
  backend: "repo"
  public_dir: "public"
  raw_base_url: "https://raw.githubusercontent.com/giuksbr/finance_automation/main/"

priceguard:
  eq_delta_max: 0.008
  cr_delta_max: 0.0035
  eq_abs_chg7d_max: 0.25
  cr_abs_chg7d_max: 0.40

window_days: 7
window_fallback_days: 10

tz: "America/Sao_Paulo"
out_dir: "out"
